version: "3"

services:
  word-web:
    container_name: word-web
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8003:80
    volumes:
      - ./:/var/www/html
      # - ./.htaccess:/var/www/html/.htaccess
      # - ./tmp:/var/www/html/tmp
    networks:
      - proxy-setting-locale_locale-network

networks:
  proxy-setting-locale_locale-network:
    external: true
