version: "3"

services:
  pdf-web:
    container_name: pdf-web
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8003:80
    volumes:
      - ./:/var/www/html
    networks:
      - locale-network

networks:
  locale-network:
    driver: bridge